.TH LDF "1" "Feb 2024"

.SH  NAME
.B ldf
-  report filesystem space info of devices and RAM/swap usage

.SH DESCRIPTION
.B  
report space info of every device starts with "/dev/" inside /etc/mtab and the RAM/swap usage

.SH USAGE
.B ldf

.B ldf --ram off --swap off

.SH
.B OPTIONS

.TP
.B [--devices, -d] <on/off>

print devices info. empty argument is consideren 'on'. default is 'on'

.TP
.B [--ram, -r] <on/off>

print ram info. empty argument is consideren 'on'. default is 'on'

.TP
.B [--swap, -s] <on/off>

print swap info. empty argument is consideren 'on'. default is 'on'

.TP
.B [--author]

print the program's author

.TP
.B [--license]

print the program's license

.TP
.B [-V, --version]

print the program's version

.TP
.B [--help]

print the help statement

.SH AUTHOR
.PP 

nodeluna 
- nodeluna@proton.me

https://github.com/nodeluna
